/*++Copyright (c) 2003-2011  Sybase, Inc.
Include File for Sybase Specific Definitions
--*/
#ifndef SYBSQLTYPES_H
#define SYBSQLTYPES_H
/*
ODBC SPECIFC DEFINITIONS , THESE SHOULD ALREADY BE DEFINED IN
STANDARD ODBC INCLUDE FILES SQLTYPES.H,SQLEXT.H, SQL.H
IF NOT DEFINED IN THE ODBC HEADER FILES, THESE VALUES WILL BE
DEFINED HERE  TAKEN FROM THE ODBC API REFERENCE
*/

/*
NOTE ANY DEFINITIONS USED HERE HAVE TO BE APPROVED BY THE OPEN GROUP
https://www.opengroup.org/projects/drda/uploads/40/9360/wpaper.htm
*/
#ifndef SQL_DRIVER_SQL_TYPE_BASE
#define SQL_DRIVER_SQL_TYPE_BASE	0x4000
#endif

#ifndef SQL_DRIVER_CONNECT_ATTR_BASE
#define SQL_DRIVER_CONNECT_ATTR_BASE 0x00004000
#endif

#ifndef SQL_DRIVER_STATEMENT_ATTR_BASE
#define SQL_DRIVER_STATEMENT_ATTR_BASE 0x00004000
#endif

/*	LOCATOR DEFINITIONS */
/*locator SQL TYPE*/
#define SQL_TEXT_LOCATOR		SQL_DRIVER_SQL_TYPE_BASE +10
#define SQL_UNITEXT_LOCATOR		SQL_DRIVER_SQL_TYPE_BASE +11
#define SQL_IMAGE_LOCATOR		SQL_DRIVER_SQL_TYPE_BASE +13

#ifndef SQL_DRIVER_STATEMENT_ATTR_BASE
#define SQL_DRIVER_STATEMENT_ATTR_BASE 0x00004000
#endif

#ifndef SQL_DRIVER_C_DATATYPES_BASE
#define SQL_DRIVER_C_DATATYPES_BASE 0x4000
#endif

#ifndef SQL_DRIVER_C_DATATYPES_END
#define SQL_DRIVER_C_DATATYPES_END 0x7FFF
#endif



/*locator C TYPE */
#define SQL_C_TEXT_LOCATOR		SQL_DRIVER_C_DATATYPES_BASE + 1
#define SQL_C_UNITEXT_LOCATOR	SQL_DRIVER_C_DATATYPES_BASE + 2
#define SQL_C_IMAGE_LOCATOR		SQL_DRIVER_C_DATATYPES_BASE + 3

/*value for the Locator size */
#define SQL_LOCATOR_SIZE		24

/* attribute to control batch without parameter arrays */
#define SQL_ATTR_BATCH_PARAMS	SQL_DRIVER_CONNECT_ATTR_BASE + 10

/*attribute to comtrol set send locator on/off*/
#define SQL_ATTR_LOBLOCATOR		SQL_DRIVER_CONNECT_ATTR_BASE + 11

/*attribute to get a verbose version string*/
#define SQL_DRIVER_VERBOSE_VER	SQL_DRIVER_CONNECT_ATTR_BASE + 12

#define SQL_LOBLOCATOR_ON				1
#define SQL_LOBLOCATOR_OFF				0

#define SQL_ATTR_LOBLOCATOR_FETCHSIZE	SQL_DRIVER_STATEMENT_ATTR_BASE + 10

/* values for SQL_ATTR_BATCH_PARAMS */
#define SQL_BATCH_DISABLED		0
#define SQL_BATCH_ENABLED		1
#define SQL_BATCH_LAST_NO_DATA	(-1)
#define SQL_BATCH_LAST_DATA		(-2)
#define SQL_BATCH_CANCEL		(-3)

/* SQLRETURN for SQLExecute and SQLExecDirect while in a batch */
#define SQL_BATCH_EXECUTING		200





#endif
